name: 'debug-gradle'
author: micalgenus
description: 'Export to atrifact from result of gradle'

inputs:
  gradle-build-path:
    required: false
    default: ./build/
    description: Path of result files for gradle.

runs:
  using: 'node12'
  main: 'dist/action/index.js'
  post: 'dist/post-action/index.js'
  post-if: 'failure()'

branding:
  icon: settings
  color: gray-dark
